server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: companyms
          uri: lb://companyms
          predicates:
            - Path=/companies/**

        - id: jobms
          uri: lb://jobms-dev
          predicates:
            - Path=/jobs/**

        - id: reviewms
          uri: lb://reviewms
          predicates:
            - Path=/reviews/**

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            gateway: TRACE


#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
